services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FOOD_DB
    ports:
      - "5432:5432"
  good_hamburguer_migration:
    container_name: good_hamburguer_migration
    hostname: good_hamburguer_migration
    image: good_hamburguer
    command: ./migration.sh
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
  good_hamburguer:
    container_name: good_hamburguer
    hostname: good_hamburguer
    image: good_hamburguer
    build: .
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      - postgres
      - good_hamburguer_migration
