<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../good_hamburguer.csproj" />
  </ItemGroup>

</Project>
